Repository croct-tech/plug-js, pull requests merged in 2020-04, with the labels that each got.

#12 Bump SDK to the latest version
  package-lock.json
  package.json
Labels: maintenance

#16 Bump SDK to the latest version
  package-lock.json
  package.json
Labels: maintenance

#17 Expose `flushed` callback
  src/plug.ts
  test/index.test.ts
Labels: enhancement

#18 Export Plug typing
  src/index.ts
Labels: enhancement

#19 Bump SDK to the latest version
  package-lock.json
  package.json
Labels: maintenance

#20 Deploy minified build to CDN bucket
  .github/workflows/deploy-published-releases.yaml
Labels: maintenance

#22 Fix build error to deploy to CDN
  .github/workflows/deploy-published-releases.yaml
Labels: bug

#23 Fix build error to deploy to CDN
  .github/workflows/deploy-published-releases.yaml
Labels: bug

#24 Bump SDK to the latest version
  package-lock.json
  package.json
Labels: maintenance

#26 Expose SDK instance
  src/index.ts
  src/plug.ts
  test/index.test.ts
Labels: enhancement

#27 Export Plug interface
  src/index.ts
  src/plug.ts
Labels: bug
