Repository croct-tech/plug-js, pull requests merged in 2020-05, with the labels that each got.

#28 Fix breaking change to API
  package-lock.json
  package.json
  rollup.min-config.js
  src/index.ts
  src/singleton.ts
Labels: bug

#29 Update readme
  README.md
Labels: documentation

#30 Bump SDK version 0.1.1
  package-lock.json
  package.json
Labels: maintenance

#31 Bump SDK version to 0.1.2
  package-lock.json
  package.json
Labels: maintenance

#32 Introduce initialization callback and pass plug instance to callbacks
  src/plug.ts
  test/index.test.ts
Labels: enhancement

#34 Bump SDK version to 0.1.4
  package-lock.json
  package.json
Labels: maintenance

#36 Log a warning when multiple plugins share the same name
  src/globalPlug.ts
  test/index.test.ts
Labels: enhancement

#37 Add support for plugins to self-register
  src/globalPlug.ts
  src/index.ts
  src/plug.ts
  src/plugin.ts
  src/singleton.ts
  test/index.test.ts
Labels: feature

#38 Do not send prerelease to CDN
  .github/workflows/deploy-published-releases.yaml
Labels: maintenance

#39 Export typing for plugin arguments
  src/index.ts
Labels: enhancement

#40 Export tab
  src/index.ts
Labels: enhancement

#42 Disable bundle step for pre-releases
  .github/workflows/deploy-published-releases.yaml
Labels: maintenance

#43 Improve Github workflow
  .github/workflows/branch-validations.yaml
Labels: maintenance

#44 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: maintenance

#45 Export concrete classes for testing purposes
  src/sdk/evaluation.ts
  src/sdk/event.ts
  src/sdk/index.ts
  src/sdk/tracking.ts
Labels: enhancement

#46 Export utility functions for error formatting
  src/sdk/validation.ts
Labels: enhancement

#47 Catch and log errors on plugin initialization
  .eslintrc.json
  src/plug.ts
  test/plug.test.ts
Labels: enhancement

#49 Allow enabling/disabling plugins
  src/plug.ts
  test/plug.test.ts
Labels: feature

#50 Bump SDK version to 0.2.0-alpha.5
  package-lock.json
  package.json
Labels: maintenance

#51 Bump SDK version to 0.2.0-alpha.6
  package-lock.json
  package.json
  src/sdk/validation.ts
Labels: maintenance

#52 Auto-detect app ID from script tag
  .github/workflows/deploy-published-releases.yaml
  README.md
  src/constants.ts
  src/plug.ts
  test/plug.test.ts
Labels: feature

#53 Fix plugin configuration augmentation
  src/plug.ts
Labels: bug

#54 Fix Github token
  .github/workflows/release-drafter.yaml
Labels: maintenance

#56 Export ES2015 modules to solve bundling issues with CommonJS
  rollup.config.js
  tsconfig.json
Labels: enhancement

#58 Fix Jest configuration to transpile ES2015 modules
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
Labels: maintenance

#57 Bump SDK version to 0.2.0-alpha.7
  package.json
Labels: maintenance

#55 Replace CDN placeholders in bundle
  .github/workflows/deploy-published-releases.yaml
  package-lock.json
  package.json
  rollup.config.js
Labels: bug

#59 Fix rollup config
  rollup.config.js
Labels: maintenance

#60 Import Typescript runtime
  package-lock.json
  package.json
  tsconfig.json
Labels: maintenance

#62 Auto-detect app ID from query-string
  .github/workflows/deploy-published-releases.yaml
  rollup.config.js
  src/constants.ts
  src/plug.ts
  test/plug.test.ts
Labels: enhancement

#63 Bump SDK to latest version 0.2.0
  package-lock.json
  package.json
Labels: maintenance

#64 Update CDN section of readme
  README.md
Labels: documentation
