Repository croct-tech/plug-js, pull requests merged in 2022-08, with the labels that each got.

#130 Updated `cart.items[*].index`
  docs/events.md
Labels: documentation

#128 Update goalId suggested length
  docs/events.md
Labels: documentation, maintenance

#125 Update documentation
  docs/evaluator.md
  docs/events.md
  docs/patch.md
  docs/plug.md
  docs/session.md
  docs/user.md
Labels: documentation, enhancement

#131 Adjust table order
  docs/events.md
  docs/session.md
Labels: documentation, enhancement
