Repository croct-tech/plug-js, pull requests merged in 2023-01, with the labels that each got.

#169 Add support for component type inference
  package-lock.json
  package.json
  src/component.ts
  src/slot.ts
  src/versioning.ts
Labels: feature

#157 Update GCP authentication to use identity federation
  .github/workflows/deploy-published-releases.yaml
Labels: enhancement

#164 Update plug documentation
  docs/plug.md
Labels: documentation, maintenance

#170 Fix slot type for hybrid components
  package-lock.json
  package.json
  src/slot.ts
  src/versioning.ts
  test/component.test.ts
  test/slot.test.ts
Labels: bug

#171 Update composer lock
  package-lock.json
Labels: maintenance
